In [ ]:
y = 100 x1 + 200x2 + 304 x3 + ... + 100

In [2]:
import numpy as np

In [10]:
m = 10
n = 4

np.random.seed(10)
c = np.random.randint(10, 200, n+1)
print(c)

[ 19 135  25  74 123]


In [11]:
X = np.random.random((m,n))
X

array([[0.74880388, 0.49850701, 0.22479665, 0.19806286],
       [0.76053071, 0.16911084, 0.08833981, 0.68535982],
       [0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412],
       [0.71457578, 0.54254437, 0.14217005, 0.37334076],
       [0.67413362, 0.44183317, 0.43401399, 0.61776698],
       [0.51313824, 0.65039718, 0.60103895, 0.8052232 ],
       [0.52164715, 0.90864888, 0.31923609, 0.09045935],
       [0.30070006, 0.11398436, 0.82868133, 0.04689632],
       [0.62628715, 0.54758616, 0.819287  , 0.19894754]])

In [38]:
np.sum([0.74880388*19, 0.49850701*135, 0.22479665*25, 0.19806286*74,   123])

224.80228796

In [41]:
np.array([1, 2, 3]) * 4

array([ 4,  8, 12])

In [40]:
np.array([1, 2, 3]) * np.array([4, 4, 4])

array([ 4,  8, 12])

In [46]:
np.array([[1, 2, 3], 
          [10,20,30]]) * np.array([4, 5, 6])

array([[  4,  10,  18],
       [ 40, 100, 180]])

In [47]:
np.array([[1, 2, 3], 
          [10,20,30]]) * np.array([[4, 5, 6],
                                   [4, 5, 6]])

array([[  4,  10,  18],
       [ 40, 100, 180]])

In [48]:
np.array([[1, 2, 3], 
          [10,20,30]]) * np.array([[4, 5, 6],
                                   [40, 50, 60]])

array([[   4,   10,   18],
       [ 400, 1000, 1800]])

In [49]:
A = np.array([
    [1, 2, 3],  
    [3, 4, 5]
])
B = np.array([10, 20, 30])
A.dot(B)

array([140, 260])

In [50]:
A * B

array([[ 10,  40,  90],
       [ 30,  80, 150]])

In [51]:
np.sum(A*B, axis=1)

array([140, 260])

In [52]:
np.sum(A*B, axis=0)

array([ 40, 120, 240])

In [54]:
c

array([ 19, 135,  25,  74, 123])

In [60]:
c[:-1]

array([ 19, 135,  25,  74])

In [59]:
c[0:c.shape[0]-1]

array([ 19, 135,  25,  74])

In [26]:
X.dot(c[:-1]) + c[-1]

array([224.80228856, 213.20516838, 214.58624728, 307.28714989,
       241.001897  , 252.02112347, 295.16573657, 270.25378888,
       168.28855072, 244.02787969])

In [65]:
X.shape

(10, 4)

In [72]:
ones = np.ones((m, 1))

In [79]:
X

array([[0.74880388, 0.49850701, 0.22479665, 0.19806286],
       [0.76053071, 0.16911084, 0.08833981, 0.68535982],
       [0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412],
       [0.71457578, 0.54254437, 0.14217005, 0.37334076],
       [0.67413362, 0.44183317, 0.43401399, 0.61776698],
       [0.51313824, 0.65039718, 0.60103895, 0.8052232 ],
       [0.52164715, 0.90864888, 0.31923609, 0.09045935],
       [0.30070006, 0.11398436, 0.82868133, 0.04689632],
       [0.62628715, 0.54758616, 0.819287  , 0.19894754]])

In [78]:
np.hstack((X, ones))

array([[0.74880388, 0.49850701, 0.22479665, 0.19806286, 1.        ],
       [0.76053071, 0.16911084, 0.08833981, 0.68535982, 1.        ],
       [0.95339335, 0.00394827, 0.51219226, 0.81262096, 1.        ],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 1.        ],
       [0.71457578, 0.54254437, 0.14217005, 0.37334076, 1.        ],
       [0.67413362, 0.44183317, 0.43401399, 0.61776698, 1.        ],
       [0.51313824, 0.65039718, 0.60103895, 0.8052232 , 1.        ],
       [0.52164715, 0.90864888, 0.31923609, 0.09045935, 1.        ],
       [0.30070006, 0.11398436, 0.82868133, 0.04689632, 1.        ],
       [0.62628715, 0.54758616, 0.819287  , 0.19894754, 1.        ]])

In [53]:
np.dot(A, B)

array([140, 260])

In [81]:
X

array([[0.74880388, 0.49850701, 0.22479665, 0.19806286],
       [0.76053071, 0.16911084, 0.08833981, 0.68535982],
       [0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412],
       [0.71457578, 0.54254437, 0.14217005, 0.37334076],
       [0.67413362, 0.44183317, 0.43401399, 0.61776698],
       [0.51313824, 0.65039718, 0.60103895, 0.8052232 ],
       [0.52164715, 0.90864888, 0.31923609, 0.09045935],
       [0.30070006, 0.11398436, 0.82868133, 0.04689632],
       [0.62628715, 0.54758616, 0.819287  , 0.19894754]])

In [83]:
X.shape[0]

10

In [90]:
w = np.array([10, 20, 30])
X = np.array([[1,2], [2, 3]])
model(X, w)

array([ 80., 110.])

In [112]:
def model(X, w):
    m = X.shape[0]
    ones = np.ones((m, 1))
    X1 = np.hstack((X, ones))
    return X1.dot(w)

In [113]:
def generateData(m, n=1):
    np.random.seed(10)
    c = np.random.randint(10, 200, n+1)
    print("Coeffs", c)
    X = np.random.random((m,n))
    y = model(X, c) + 2*np.random.random((m)) - 2*np.random.random((m))
    return X, y

In [101]:
19*0.63364823 + 135*0.74880388 + 25

138.12784016999998

In [106]:
X, y = generateData(10, 2)

Coeffs [ 19 135  25]


In [114]:
def lossf(X, y, w):
    diff = model(X, w) - y
    return np.sum(diff*diff)

In [117]:
m = 1000
n = 4
X, y = generateData(m,n)

Coeffs [ 19 135  25  74 123]


In [118]:
w = np.random.random(n+1)

In [119]:
lossf(X, y, w)

62632228.82337599

In [126]:
1e-10

1e-10

In [132]:
w

array([0.99193634, 0.20693837, 0.70043623, 0.14935247, 0.19871698])

In [134]:
n

4

In [145]:
numw = w.shape[0]
a = np.zeros((numw, numw))
np.fill_diagonal(a, 1)
neww = w + a
neww

array([[1.99193634, 0.20693837, 0.70043623, 0.14935247, 0.19871698],
       [0.99193634, 1.20693837, 0.70043623, 0.14935247, 0.19871698],
       [0.99193634, 0.20693837, 1.70043623, 0.14935247, 0.19871698],
       [0.99193634, 0.20693837, 0.70043623, 1.14935247, 0.19871698],
       [0.99193634, 0.20693837, 0.70043623, 0.14935247, 1.19871698]])

In [151]:
neww.T

array([[1.99193634, 0.99193634, 0.99193634, 0.99193634, 0.99193634],
       [0.20693837, 1.20693837, 0.20693837, 0.20693837, 0.20693837],
       [0.70043623, 0.70043623, 1.70043623, 0.70043623, 0.70043623],
       [0.14935247, 0.14935247, 0.14935247, 1.14935247, 0.14935247],
       [0.19871698, 0.19871698, 0.19871698, 0.19871698, 1.19871698]])

In [156]:
ones = np.ones((m, 1))
X1 = np.hstack((X, ones))

In [157]:
X1 @ neww.T 

array([[1.98048377, 1.73018689, 1.45647653, 1.42974275, 2.23167988],
       [1.91287785, 1.32145798, 1.24068695, 1.83770696, 2.15234714],
       [2.57875785, 1.62931277, 2.13755676, 2.43798546, 2.6253645 ],
       ...,
       [0.4310883 , 0.67148965, 0.44229076, 0.80932391, 1.39228899],
       [1.69690582, 2.27456034, 2.37487199, 1.80931637, 2.40596222],
       [1.56429859, 1.88438148, 2.1545782 , 1.25980955, 2.25879843]])

In [169]:
yy = np.array([1,2,3])
ypred = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [179]:
MyA = np.array([1,2,3,4,5,6, 7, 8, 9, 10, 11, 12])
MyA.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [186]:
MyA.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
MyA.reshape()

In [188]:
yy = np.array([1,2,3])
ypred = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [190]:
yy1 = yy.reshape(-1, 1)

In [193]:
diff= ypred - yy1
diff

array([[0, 1],
       [1, 2],
       [2, 3]])

In [195]:
sqdiff = diff*diff

In [197]:
sqdiff

array([[0, 1],
       [1, 4],
       [4, 9]])

In [198]:
np.sum(sqdiff, axis=0)

array([ 5, 14])

In [154]:
A = np.array([
        [1,2,3],
        [2, 3, 4]
    ])
B = np.array([
    [10, 20],
    [20, 30],
    [30, 40],
])
A @ B

array([[140, 200],
       [200, 290]])

In [130]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [199]:
X

array([[0.74880388, 0.49850701, 0.22479665, 0.19806286],
       [0.76053071, 0.16911084, 0.08833981, 0.68535982],
       [0.95339335, 0.00394827, 0.51219226, 0.81262096],
       ...,
       [0.03879931, 0.27920065, 0.05000176, 0.41703491],
       [0.29094359, 0.86859811, 0.96890977, 0.40335415],
       [0.30550016, 0.62558304, 0.89577976, 0.00101112]])

In [215]:
X1.shape

(1000, 5)

In [213]:
result = X1 @ w.reshape(-1, 1)
result.shape

(1000, 1)

In [209]:
X1 @ neww.reshape()

array([[3.39744294, 1.05106772, 2.09508075, 0.59685942, 1.53060819],
       [3.44207307, 0.72853585, 1.98185793, 1.08911051, 1.53719979],
       [4.209082  , 0.68315204, 2.81113244, 1.3028189 , 1.65221989],
       ...,
       [1.80944202, 0.64859323, 1.30030611, 0.68363455, 1.35471709],
       [3.79426993, 1.59946421, 3.4427144 , 0.93083805, 1.70182974],
       [3.11057121, 1.21077869, 2.87652523, 0.4233611 , 1.56194659]])

In [201]:
X @ w.reshape(-1, 1)T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [220]:
def compute_grad(X, y, w):
    delta = 1e-10
    ones = np.ones((m, 1))
    X1 = np.hstack((X, ones))
    
    # Loss before increaseing w
    ww = w.reshape(-1, 1)
    ypred = X1 @ ww
    error = ypred - y.reshape(-1, 1)
    loss = np.sum(error * error)
    
    eps = 1e-8
    # Loss after increasing w
    numw = w.shape[0]
    a = np.zeros((numw, numw))
    np.fill_diagonal(a, eps)
    neww = w + a
    ypred = X1 @ neww
    error = ypred - y.reshape(-1, 1)
    loss1 = np.sum(error * error, axis=0)
    
    return (loss1 - loss)/eps

In [222]:
g = compute_grad(X, y, w)

In [225]:
g

array([-8.81334448e+13,  2.98021781e+13, -4.44715474e+13,  3.84982785e+13,
        3.10433252e+13])

In [1]:
# Training


def fit(lossf, X, y, w, epoch):
    for i in range(epoch):
        grad = compute_grad(lossf, X, y, w)
        w -= eta * grad
        print(lossf(X, y, w))

NameError: name 'np' is not defined

In [ ]:

def initializeW(m, n=1):
    pass

def model(X, W):
    return np.sum(W*X)

def sqloss(X, y, W):
    ypred = model(X, W)
    diff = ypred - y
    return np.sum(diff*diff)

def grad(lossf, W, X, y, idx):
    l1 = lossf(X, y, W)
    ...

def fit(X, y, lossf, W):
    ...

def train(X, y, epoch=10):
    W = initializeW
    for i in 
    