In [1]:
import numpy as np

In [4]:
# Numpy:
#     1. An efficient array
#     2. Power set of functions that eliminate the need of for-loops

In [3]:
m = 10 # Instances, rows, samples, datapoints, experiences
n = 4 # features, columns, attributes, dimensions, characterstics, 

In [5]:
X = np.random.random((m,n)) # m rows , n columns
X

array([[0.80448084, 0.43288127, 0.19885455, 0.5032878 ],
       [0.80987313, 0.11499867, 0.85692999, 0.86052654],
       [0.7813267 , 0.09934062, 0.84495212, 0.09642656],
       [0.00330967, 0.98705401, 0.57833947, 0.1544363 ],
       [0.76962738, 0.53502119, 0.96575207, 0.97832631],
       [0.01192424, 0.88629141, 0.8307215 , 0.79081554],
       [0.45152953, 0.82337521, 0.47451287, 0.77680343],
       [0.22548647, 0.27478504, 0.26868688, 0.78626736],
       [0.92442682, 0.41422572, 0.12798356, 0.88232037],
       [0.53432265, 0.81227191, 0.16954299, 0.95397301]])

In [29]:
def model(X, w):
    m = X.shape[0]
    ones = np.ones((m, 1))
    X1 = np.hstack((X, ones))
    return X1.dot(w.T)

In [30]:
w = np.array([10, 20, 30, 40])
X = np.array([[1,2, 5], [2, 3, 6]])
model(X, w)

array([240., 300.])

In [33]:
w = np.array([[10, 20, 30, 40],
              [11, 20, 30, 40],
              [10, 21, 30, 40],
              [11, 20, 31, 40],
              [10, 20, 30, 41]
             ])
X = np.array([[1,2, 5], [2, 3, 6]])
model(X, w)

array([[240., 241., 242., 246., 241.],
       [300., 302., 303., 308., 301.]])

In [24]:
def generateData(m, n=1):
    np.random.seed(10)
    w = np.random.randint(10, 200, n+1)
    print("Coeffs",w)
    X = np.random.random((m,n))
    y = model(X, w) + 2*np.random.random((m)) - 2*np.random.random((m))
    return X, y

In [25]:
X, y = generateData(10, 2)

Coeffs [ 19 135  25]


In [36]:
y = np.array([1, 2])
y = y.reshape(-1, 1)
print(y)
ypred = np.array([[1.1, 1.2], [1.9, 2.1]])
ypred - y

[[1]
 [2]]


array([[ 0.1,  0.2],
       [-0.1,  0.1]])

In [119]:
X = np.array([[1], [2], [3]])
y = np.array([5.1, 7.9, 11.1]).reshape(-1, 1) # 3 x 1

In [120]:
w = np.array([[1, 2]]) # initial guess

In [121]:
# iteration would start
ypred = model(X, w)
print(ypred)

[[3.]
 [4.]
 [5.]]


In [122]:

d = ypred - y
print("error: ", d)
initial_loss = np.sum(d*d)
print("loss: ", initial_loss)

error:  [[-2.1]
 [-3.9]
 [-6.1]]
loss:  56.83


In [123]:
def lossf(X, y, w): #X: m*n, y: m * 1, w: -1 * n + 1
    pred = model(X, w)
    error = pred - y #.reshape(-1, 1)
    sq_error = error*error
    loss = np.sum(sq_error,axis=0)
    return loss

In [124]:
lossf(X, y, w)

array([56.83])

In [140]:
w

array([[1, 2]])

In [61]:
delta = 0.01
w_ = np.array([[1+0.01, 2], [1, 2 + 0.01]])

In [141]:
def incr_w(delta, w):
#     print(w.shape)
    numw = w.shape[-1]
#     print(numw)
    a = np.zeros((numw, numw))
#     print(a)
    np.fill_diagonal(a, delta)
#     print(a)
    return w +  a

In [143]:
w_ = incr_w(delta, w)
w_

array([[1.01, 2.  ],
       [1.  , 2.01]])

In [62]:
new_pred = model(X, w_)
new_pred

array([[3.01, 3.01],
       [4.02, 4.01],
       [5.03, 5.01]])

In [63]:
new_error = new_pred - y.reshape(-1, 1)
new_error

array([[-2.09, -2.09],
       [-3.88, -3.89],
       [-6.07, -6.09]])

In [65]:
sq_error = new_error*new_error
sq_error

array([[ 4.3681,  4.3681],
       [15.0544, 15.1321],
       [36.8449, 37.0881]])

In [72]:
loss = np.sum(sq_error,axis=0)
loss

array([56.2674, 56.5883])

In [145]:
new_loss = lossf(X, y, w_)
new_loss    

array([56.2674, 56.5883])

In [73]:
initial_loss

56.83

In [75]:
grads = (loss - initial_loss)/delta
grads

array([-56.26, -24.17])

In [77]:
w

array([1, 2])

array([-56.26, -24.17])

In [81]:
eta = 0.01
w = w - eta * grads

In [82]:
w

array([1.5626, 2.2417])

In [2]:
def model(X, w):
    m = X.shape[0]
    ones = np.ones((m, 1))
    X1 = np.hstack((X, ones))
    return X1.dot(w.T)

In [3]:
def lossf(X, y, w): #X: m*n, y: m * 1, w: -1 * n
    pred = model(X, w)
    error = pred - y #.reshape(-1, 1)
    sq_error = error*error
    loss = np.sum(sq_error,axis=0)
    return loss

In [4]:
def incr_w(delta, w):
    numw = w.shape[-1]
    a = np.zeros((numw, numw))
    np.fill_diagonal(a, delta)
    return w +  a

In [5]:
def compute_grad(X, y, w):
    delta = 1e-10
    initial_loss = lossf(X, y, w)
    w_ = incr_w(delta, w)
    new_loss = lossf(X, y, w_)
    grads = (new_loss - initial_loss)/delta
    return grads

In [6]:
def new_weights(X, y, w):
    eta = 0.01
    grads = compute_grad(X, y, w)
    w = w - eta * grads
    return w

In [12]:
w = np.array([[1, 2]])
X = np.array([[1], [2], [3]])
y = np.array([5.1, 7.9, 11.1]).reshape(-1, 1) # 3 x 1

for epoch in range(1000):
    w = new_weights(X, y, w)
    print(epoch, "loss: " , lossf(X, y, w), ", weights: ", w)

0 loss:  [25.43088504] , weights:  [[1.5640004  2.24199949]]
1 loss:  [11.45121768] , weights:  [[1.94104031 2.40179948]]
2 loss:  [5.22620591] , weights:  [[2.19333325 2.50676672]]
3 loss:  [2.45337781] , weights:  [[2.36238789 2.57516072]]
4 loss:  [1.21738314] , weights:  [[2.47589998 2.61916454]]
5 loss:  [0.66556632] , weights:  [[2.55234827 2.64690671]]
6 loss:  [0.41834939] , weights:  [[2.60406195 2.66381051]]
7 loss:  [0.30675387] , weights:  [[2.63926735 2.67349445]]
8 loss:  [0.25555535] , weights:  [[2.66345316 2.6783727 ]]
9 loss:  [0.23126569] , weights:  [[2.68028155 2.68005596]]
10 loss:  [0.21897659] , weights:  [[2.692196   2.67961882]]
11 loss:  [0.21205103] , weights:  [[2.70082686 2.67777817]]
12 loss:  [0.20753407] , weights:  [[2.70726196 2.67501226]]
13 loss:  [0.20410995] , weights:  [[2.71222714 2.67164009]]
14 loss:  [0.20119264] , weights:  [[2.71620673 2.66787442]]
15 loss:  [0.19852098] , weights:  [[2.71952392 2.66385715]]
16 loss:  [0.19597839] , weights

245 loss:  [0.03281646] , weights:  [[2.94741457 2.15287237]]
246 loss:  [0.03272807] , weights:  [[2.94779381 2.15201028]]
247 loss:  [0.03264096] , weights:  [[2.94817031 2.15115441]]
248 loss:  [0.0325551] , weights:  [[2.94854409 2.15030471]]
249 loss:  [0.03247047] , weights:  [[2.94891518 2.14946113]]
250 loss:  [0.03238707] , weights:  [[2.94928359 2.14862364]]
251 loss:  [0.03230485] , weights:  [[2.94964935 2.14779219]]
252 loss:  [0.03222382] , weights:  [[2.95001247 2.14696674]]
253 loss:  [0.03214396] , weights:  [[2.95037297 2.14614724]]
254 loss:  [0.03206524] , weights:  [[2.95073087 2.14533365]]
255 loss:  [0.03198766] , weights:  [[2.95108619 2.14452593]]
256 loss:  [0.03191118] , weights:  [[2.95143894 2.14372403]]
257 loss:  [0.03183581] , weights:  [[2.95178916 2.14292791]]
258 loss:  [0.03176152] , weights:  [[2.95213684 2.14213754]]
259 loss:  [0.0316883] , weights:  [[2.95248202 2.14135286]]
260 loss:  [0.03161613] , weights:  [[2.95282471 2.14057385]]
261 loss: 

415 loss:  [0.0271916] , weights:  [[2.98463655 2.06825804]]
416 loss:  [0.02718406] , weights:  [[2.98474735 2.06800614]]
417 loss:  [0.02717662] , weights:  [[2.98485736 2.06775606]]
418 loss:  [0.02716929] , weights:  [[2.98496654 2.06750782]]
419 loss:  [0.02716207] , weights:  [[2.98507497 2.06726133]]
420 loss:  [0.02715495] , weights:  [[2.98518259 2.06701668]]
421 loss:  [0.02714793] , weights:  [[2.98528949 2.06677384]]
422 loss:  [0.02714102] , weights:  [[2.9853956  2.06653265]]
423 loss:  [0.0271342] , weights:  [[2.98550089 2.06629322]]
424 loss:  [0.02712748] , weights:  [[2.98560545 2.06605552]]
425 loss:  [0.02712086] , weights:  [[2.98570926 2.06581953]]
426 loss:  [0.02711433] , weights:  [[2.9858123  2.06558518]]
427 loss:  [0.02710789] , weights:  [[2.98591466 2.06535257]]
428 loss:  [0.02710155] , weights:  [[2.98601625 2.06512168]]
429 loss:  [0.02709531] , weights:  [[2.98611712 2.06489251]]
430 loss:  [0.02708915] , weights:  [[2.98621723 2.06466495]]
431 loss: 

609 loss:  [0.02669832] , weights:  [[2.99622716 2.04190985]]
610 loss:  [0.02669787] , weights:  [[2.99625437 2.041848  ]]
611 loss:  [0.02669742] , weights:  [[2.99628136 2.04178653]]
612 loss:  [0.02669698] , weights:  [[2.9963082  2.04172555]]
613 loss:  [0.02669654] , weights:  [[2.99633484 2.04166503]]
614 loss:  [0.02669611] , weights:  [[2.99636128 2.04160495]]
615 loss:  [0.02669569] , weights:  [[2.99638755 2.0415453 ]]
616 loss:  [0.02669527] , weights:  [[2.9964136 2.0414861]]
617 loss:  [0.02669486] , weights:  [[2.99643944 2.0414273 ]]
618 loss:  [0.02669446] , weights:  [[2.99646514 2.04136901]]
619 loss:  [0.02669406] , weights:  [[2.99649065 2.04131112]]
620 loss:  [0.02669366] , weights:  [[2.99651591 2.0412535 ]]
621 loss:  [0.02669328] , weights:  [[2.99654101 2.04119641]]
622 loss:  [0.02669289] , weights:  [[2.99656596 2.04113965]]
623 loss:  [0.02669252] , weights:  [[2.99659075 2.04108329]]
624 loss:  [0.02669214] , weights:  [[2.99661535 2.04102737]]
625 loss: 

797 loss:  [0.02666875] , weights:  [[2.99903219 2.03553346]]
798 loss:  [0.02666872] , weights:  [[2.99903918 2.03551759]]
799 loss:  [0.02666869] , weights:  [[2.99904613 2.0355019 ]]
800 loss:  [0.02666866] , weights:  [[2.99905301 2.03548632]]
801 loss:  [0.02666863] , weights:  [[2.99905981 2.03547078]]
802 loss:  [0.0266686] , weights:  [[2.99906657 2.03545536]]
803 loss:  [0.02666858] , weights:  [[2.99907326 2.03544007]]
804 loss:  [0.02666855] , weights:  [[2.99907994 2.03542488]]
805 loss:  [0.02666852] , weights:  [[2.99908657 2.03540979]]
806 loss:  [0.0266685] , weights:  [[2.99909318 2.03539474]]
807 loss:  [0.02666847] , weights:  [[2.99909972 2.03537988]]
808 loss:  [0.02666844] , weights:  [[2.99910621 2.03536512]]
809 loss:  [0.02666842] , weights:  [[2.99911266 2.03535049]]
810 loss:  [0.02666839] , weights:  [[2.99911908 2.03533592]]
811 loss:  [0.02666837] , weights:  [[2.99912543 2.03532143]]
812 loss:  [0.02666834] , weights:  [[2.99913174 2.03530709]]
813 loss: 